{% set name = "napari-svg" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 9e2f295bae33e45c0195032bbb2cb3f372e8016f0f3d69715dac3cb3505d10f6

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.9
    - pip
    - setuptools_scm
  run:
    - imageio >=2.5.0
    - numpy >=1.16.0
    - napari-plugin-engine >=0.1.4
    - vispy >=0.6.4
    - python >=3.9

test:
  commands:
    - xvfb-run --auto-servernum python -c "import napari_svg"

about:
  home: https://github.com/napari/napari-svg
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: An io plugin for reading and writing svg files with napari

  # The remaining entries in this section are optional, but recommended.
  description: |
    An io plugin for reading and writing svg files with napari
  doc_url: https://github.com/napari/napari-svg
  dev_url: https://github.com/napari/napari-svg

extra:
  recipe-maintainers:
    - sofroniewn
    - tlambert03
    - jni
