{% set name = "napari-svg" %}
{% set version = "0.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 031f13b34b0948afbdcb11eb00728fe32ef7e4e3aa3905f923001d6871a08ad9

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
    - setuptools_scm
  run:
    - imageio >=2.5.0
    - numpy >=1.16.0
    - vispy >=0.6.4
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
  commands:
    - xvfb-run --auto-servernum python -c "import napari_svg"

about:
  home: https://github.com/napari/napari-svg
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: An io plugin for reading and writing svg files with napari

  # The remaining entries in this section are optional, but recommended.
  description: |
    An io plugin for reading and writing svg files with napari
  doc_url: https://github.com/napari/napari-svg
  dev_url: https://github.com/napari/napari-svg

extra:
  recipe-maintainers:
    - conda-forge/napari
    - sofroniewn
    - jni
