{% set name = "napari-svg" %}
{% set version = "0.1.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 18e642c888a71e09c9d1097f25bced1e7ef5dde1771469647bcd77975800f77d

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
    - setuptools_scm
  run:
    - imageio >=2.5.0
    - numpy >=1.16.0
    - napari-plugin-engine >=0.1.4
    - vispy >=0.6.4
    - python >=3.7

test:
  commands:
    - xvfb-run --auto-servernum python -c "import napari_svg"

about:
  home: https://github.com/napari/napari-svg
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: An io plugin for reading and writing svg files with napari

  # The remaining entries in this section are optional, but recommended.
  description: |
    An io plugin for reading and writing svg files with napari
  doc_url: https://github.com/napari/napari-svg
  dev_url: https://github.com/napari/napari-svg

extra:
  recipe-maintainers:
    - sofroniewn
    - tlambert03
    - jni
