{% set name = "napari-svg" %}
{% set version = "0.1.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 7e0cb5af0e98948cdc9719becec6c0641159444adf33b8b9ba538d0faee75b55

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools_scm
  run:
    - imageio
    - numpy
    - napari-plugin-engine
    - vispy
    - python >=3.6

test:
  imports:
    - napari_svg

about:
  home: https://github.com/napari/napari-svg
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: An io plugin for reading and writing svg files with napari

  # The remaining entries in this section are optional, but recommended.
  description: |
    An io plugin for reading and writing svg files with napari
  doc_url: https://github.com/napari/napari-svg
  dev_url: https://github.com/napari/napari-svg

extra:
  recipe-maintainers:
    - sofroniewn
    - tlambert03
    - jni
